services:
  app:
    build: .
    image: akira:latest
    container_name: akira-server
    environment:
      - DATABASE_URL=postgresql://devuser:devpassword@db:5432/devdb
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: akira-db
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "devuser", "-d", "devdb"]
      interval: 5s
      timeout: 5s
      retries: 5